#!/bin/bash

## This script reads through raw logs and generates lists of summoners and games.
## The outputs are used for generating processed logs.

mkdir -p input
mongo --quiet scripts/RawGameIds.js | shuf > input/games
mongo --quiet scripts/RawSummonerIds.js | shuf > input/summoners
